blog/urls.py
from django.conf.urls import url, include
from django.views.generic import DetailView, ListView
from .models import Post

app_name = 'blog'

urlpatterns = [
    url(r'^$', ListView.as_view(queryset=Post.objects.all().order_by("-date")[:25], template_name='blog/blog.html')),
    url(r'(?P<pk>\d+)$', DetailView.as_view(model=Post, template_name='blog/post.html'), name='post')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('personal.urls')),
    url(r'^blog/', include('blog.urls')),
]

personal/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
]

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=140)
    body = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title

personal/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return None

personal/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'personal/home.html')


def contact(request):
    return render(request, 'personal/contact.html', {'content': ['If you want mail me, this is my email: ', '15_yurchik@ukr.net']})

blog/templates/blog/blog.html
{% extends 'personal/base.html' %}

{% block content %}
    {% for post in object_list %}
        <h5>{{ post.date|date:"Y-m-d" }}&nbsp;<a href="{% url 'blog:post' post.pk %}">{{ post.title }}</a></h5>
    {% endfor %}
{% endblock %}

blog/templates/blog/post.html
{% extends 'personal/base.html' %}

{% block content %}
    <h3>{{ post.title }}</h3>
    <h5>on {{ post.date }}</h5>
    {{ post.body|safe|linebreaks }}
{% endblock %}

personal/templates/personal/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style>
        html, body {
            height: 100%;
        }
    </style>
</head>
<body class="body" style="background-color: #f6f6f6;">
    <div class="container-fluid" style="min-height: 95%">
        <div class="row">
            <div class="col-sm-2">
                <br>
                <center>
                    <img src="{% static 'img/profile.jpg' %}" class="img-responsive" style="max-height: 100px" alt="face"/>
                </center>
            </div>
            <div class="col-sm-10">
                <hr/>
            </div>
            <div class="col-sm-10">
                <br>
                <center>
                    <h3>Programming, Teaching, Entrepreneurship</h3>
                </center>
            </div>
        </div><hr/>
        <div class="row">
            <div class="col-sm-2">
                <div class="well bs-sidebar" id="sidebar" style="background-color: #fff">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="/">Home</a></li>
                        <li><a href="/blog/">Blog</a></li>
                        <li><a href="/contact/">Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-10">
                <div class="container-fluid">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="container-fluid" style="margin-left: 15px">
            <p>
                <a href="#" target="_blank">Contact</a> |
                <a href="#" target="_blank">LinkedIn</a> |
                <a href="#" target="_blank">Twitter</a> |
                <a href="#" target="_blank">Google+</a>
            </p>
        </div>
    </footer>
</body>
</html>

personal/templates/personal/contact.html
{% extends "personal/base.html" %}

{% block content %}

    {% for c in content %}
        <p>{{ c }}</p>
    {% endfor %}

{% endblock %}

personal/templates/personal/home.html
{% extends "personal/base.html" %}

{% block content %}
    <p>HEY! Welcom to my web site!</p>
    {% include 'personal/includes/htmlsnippets.html' %}
{% endblock %}

personal/templates/personal/includes/htmlsnippets.html
{% block content %}
    <p>Look at me i'm included!!!</p>
{% endblock %}